### ISSUE TITLE
Get data assignment

### ISSUE THREAD

**Issue by maryfollo** [maryfollo/soc513_spring_project#1]
@AaronGullickson 
I believe I am done with this assignment. Thanks for your help!

Mary

**Comment by AaronGullickson** [comment]
Hi @maryfollo . The write up looks good. Be sure to include a brief description in the input/README file as well. 

On your code, the `read_dta` command works fine but the `read.csv` command did not work for two reasons: (1) there was a typo in the file name with a "." instead of a "_" and (2) I don't think `read.csv` can find data in a zip file, you want `read_csv` instead.

Also, you were saving all of your datasets as "dat" so they were overwriting each other. 

So I fixed a bit of the code in commit 5e77c75da44b564cb2edb33b972162030d3846de and pushed that to GitHub. You can pull it down to get the changes.
